export main_dir=/home/swnie/tdnn
export qm_method=osvmp2 #osvmp2 osvccsd osvccsd-t
export osv_tol=1e-4 #1e-4 1e-5 1e-6
#export int_type=rhfint #mp2int rhfint
export no_train=50
export no_valid=5
#export pairtype_list=[diag] #If commented, all pair types will be used
#export y_log=log
export interpolate=0
export train_pair=1
#export use_mbe=1
#export ene_comp=DC
export use_osv=1 # only affect input, now the NN shall take arbitrary input except the last coloumns
#export split_offdiagc="[1.5e-3, 4.9e-5, 1.5e-6]"
export Epochs=400
export learning_rate=0.001
export decay=0.0001
export loss_function=mae # #mse very bad it seems different type of loss function affects a lot
export pca=0
export energy_shift=0
export regularize=0
export act_l1_value=0.00001
export kernel_regularize=0
export kernel_l2_value=0.000001
export batch_norm=0
export no_hidden_layers=4
export no_neuron_hidden_layer=100
export activation_hidden_layer=relu #can be gelu, sigmoid, tanh, ...
#export dropout_list=[0.2,0.2,0.2] #if this is None, then can't evaluate with ast 
export x_scaler=std
export y_scaler=std
#export x_scaler=MinMax #return None if not in the environment 
#export x_scaler=RobustScaler
#export y_scaler=std # Or MinMax
#export file_samp=test/20220623235135_mp2int_8_locj_lock_locf_fenemat_nonmbe_ccpvtz_osvccsd_1e-4_ep200_tr50_xstd_ystd_xpca/mols_samp.hdf5
#export file_sample=/data1/qjliang/ML/new/mols_sample/mol_samp_c2.hdf5
export qm_method=osvmp2
#export systems_train=[ice_samp_032]
#export systems_train=[cam_water_molpro]
export systems_train=[qm7b]
export systems_test=[qm7b]
export no_train=[200]
export no_valid=[40]
#export descriptor="$int_type"_8_locj_lock_locf_fenemat_nonmbe_ccpvtz
#export descriptor=mp2int_pm_6_locj_lock_locf_ccpvtz
#export descriptor=mp2int_pm_8_locj_lock_locf_fenemat_wpnv2_ccpvtz
#export descriptor=mp2int_3_locj_lock_locf_nonmbe_631g
#export descriptor=mp2int_6_locj_lock_locf_fenemat_wpnv2_nonmbe_631g
#export load_model="test/20220727031113_mp2int_pm_8_locj_lock_locf_fenemat_wpnv2_631g_osvmp2_1e-4_ep200_tr10_xstd_ystd"
#export load_model="/data1/qjliang/ML/new/test/20220729172813_mp2int_pm_8_locj_lock_locf_fenemat_wpnv2_ccpvtz_osvmp2_1e-4_ep200_tr450_xstd_ystd"

#export descriptor=mp2int_pm_8_locj_lock_locf_fenemat_wpnv2_631g
#export descriptor=mp2int_boys_8_locj_lock_locf_fenemat_wpnv2_ccpvtz
export descriptor=mp2int_pm_8_locj_lock_locf_fenemat_wpnv2_ccpvtz
export load_model="test/20241109231339_mp2int_pm_8_locj_lock_locf_fenemat_wpnv2_ccpvtz_osvmp2_1e-4_ep400_tr200_xstd_ystd"
python3.9 ml_osvmp2.py 
